Plugins/Stox.Plugin.DiscountRules.HasOneProduct/Models/RequirementModel.cs
using Stox.Web.Framework;

namespace Stox.Plugin.DiscountRules.HasOneProduct.Models
{
    public class RequirementModel
    {
        [StoxResourceDisplayName("Plugins.DiscountRules.HasOneProduct.Fields.Products")]
        public string Products { get; set; }

        public int DiscountId { get; set; }

        public int RequirementId { get; set; }
    }
}

Plugins/Stox.Plugin.DiscountRules.HasOneProduct/Controllers/DiscountRulesHasOneProductController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Stox.Core.Domain.Discounts;
using Stox.Plugin.DiscountRules.HasOneProduct.Models;
using Stox.Services.Configuration;
using Stox.Services.Discounts;
using Stox.Services.Security;
using Stox.Web.Framework.Controllers;

namespace Stox.Plugin.DiscountRules.HasOneProduct.Controllers
{
    [AdminAuthorize]
    public class DiscountRulesHasOneProductController : Controller
    {
        private readonly IDiscountService _discountService;
        private readonly ISettingService _settingService;
        private readonly IPermissionService _permissionService;

        public DiscountRulesHasOneProductController(IDiscountService discountService,
            ISettingService settingService, IPermissionService permissionService)
        {
            this._discountService = discountService;
            this._settingService = settingService;
            this._permissionService = permissionService;
        }

        public ActionResult Configure(int discountId, int? discountRequirementId)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageDiscounts))
                return Content("Access denied");

            var discount = _discountService.GetDiscountById(discountId);
            if (discount == null)
                throw new ArgumentException("Discount could not be loaded");

            DiscountRequirement discountRequirement = null;
            if (discountRequirementId.HasValue)
            {
                discountRequirement = discount.DiscountRequirements.FirstOrDefault(dr => dr.Id == discountRequirementId.Value);
                if (discountRequirement == null)
                    return Content("Failed to load requirement.");
            }

            var restrictedProductIds = _settingService.GetSettingByKey<string>(string.Format("DiscountRequirement.RestrictedProductIds-{0}", discountRequirementId.HasValue ? discountRequirementId.Value : 0));

            var model = new RequirementModel();
            model.RequirementId = discountRequirementId.HasValue ? discountRequirementId.Value : 0;
            model.DiscountId = discountId;
            model.Products = restrictedProductIds;

            //add a prefix
            ViewData.TemplateInfo.HtmlFieldPrefix = string.Format("DiscountRulesHasOneProduct{0}", discountRequirementId.HasValue ? discountRequirementId.Value.ToString() : "0");

            return View("Stox.Plugin.DiscountRules.HasOneProduct.Views.DiscountRulesHasOneProduct.Configure", model);
        }

        [HttpPost]
        public ActionResult Configure(int discountId, int? discountRequirementId, string productIds)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageDiscounts))
                return Content("Access denied");

            var discount = _discountService.GetDiscountById(discountId);
            if (discount == null)
                throw new ArgumentException("Discount could not be loaded");

            DiscountRequirement discountRequirement = null;
            if (discountRequirementId.HasValue)
                discountRequirement = discount.DiscountRequirements.FirstOrDefault(dr => dr.Id == discountRequirementId.Value);

            if (discountRequirement != null)
            {
                //update existing rule
                _settingService.SetSetting(string.Format("DiscountRequirement.RestrictedProductIds-{0}", discountRequirement.Id), productIds);
            }
            else
            {
                //save new rule
                discountRequirement = new DiscountRequirement()
                {
                    DiscountRequirementRuleSystemName = "DiscountRequirement.HasOneProduct"
                };
                discount.DiscountRequirements.Add(discountRequirement);
                _discountService.UpdateDiscount(discount);

                _settingService.SetSetting(string.Format("DiscountRequirement.RestrictedProductIds-{0}", discountRequirement.Id), productIds);
            }
            return Json(new { Result = true, NewRequirementId = discountRequirement.Id }, JsonRequestBehavior.AllowGet);
        }
        
    }
}

Plugins/Stox.Plugin.DiscountRules.HasOneProduct/Views/DiscountRulesHasOneProduct/Configure.cshtml
@{
    Layout = "";
}
@model Nop.Plugin.DiscountRules.HasOneProduct.Models.RequirementModel
@using Stox.Web.Framework;

    <script type="text/javascript">
        $(document).ready(function () {
            $('#saveHasOneProductrequirement@(Model.RequirementId)').click(function () {
                var productIds = $("#@Html.FieldIdFor(model => model.Products)").val();
                var discountId = @Model.DiscountId;
                var requirementId = @Model.RequirementId;
                $.ajax({
                    cache:false,
                    type: "POST",
                    url: "@(Url.Action("Configure", "DiscountRulesHasOneProduct"))",
                    data: { "discountId": discountId, "discountRequirementId": requirementId, "productIds": productIds },
                    success: function (data) {
                         $('#pnl-save-requirement-result@(Model.RequirementId)').fadeIn("slow").delay(1000).fadeOut("slow");
                         //notify parent if it's a new requirement
                         @if (Model.RequirementId == 0)
                         {
                            <text>$("#discountRequirementContainer").trigger('nopnewdiscountruleadded', [data.NewRequirementId]);</text>
                         }
                    },
                    error:function (xhr, ajaxOptions, thrownError){
                        alert('@Html.Raw(HttpUtility.JavaScriptStringEncode(T("Admin.Promotions.Discounts.Requirements.FailedToSave").Text))');
                    }  
                });
            });
        });
    </script>
    
    <table class="adminContent">
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.Products):
            </td>
            <td class="adminData">
                <div>@Html.EditorFor(model => model.Products) <input type="button" id="saveHasOneProductrequirement@(Model.RequirementId)" class="t-button" value="@T("Admin.Common.Save")" /></div>
                <div id="pnl-save-requirement-result@(Model.RequirementId)" style="display:none;">@T("Admin.Promotions.Discounts.Requirements.Saved")</div>
            </td>
        </tr>
    </table>